### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by alex-silverman**
converting data.frame/tidyr stuff to data.table because it's much faster

### CODE REVIEW

**Review by kiadso — CHANGES_REQUESTED** [review]
I'm unable to get it to run, I'm getting an error message: Warning: Error in if: argument is of length zero
  1: shiny::runApp

**Comment by alex-silverman** [comment]
> I'm unable to get it to run, I'm getting an error message: Warning: Error in if: argument is of length zero 1: shiny::runApp

this should be fixed now. I had to add the upload filepath to the importFile function

**Comment by kiadso** [comment]
Hi @alex-silverman , when I try to run this, I get "Eva has crashed..." and a Warning "One or more parsing issues, call problems() on your data frame for details, e.g.: dat <- vroom(...)/ problems(dat)", then another Warning: "Error in if: argument is of length zero."
(I was using good_small.zip.)

**Review by kiadso — CHANGES_REQUESTED** [review]
crashes if I use good.zip or good_small.zip (see comment)

**Comment by alex-silverman** [comment]
> crashes if I use good.zip or good_small.zip (see comment)

Looks like this one was due to the perm_destinations being updated to perm_livingsituation. I've pushed a fix for that.

**Review by kiadso — CHANGES_REQUESTED** [review]
I put a browser at the top of 04_initial_data_prep and stepped through the code. Whenever I use good.zip and I get to line 161, I get this: 
image and can't go further with testing.

**Comment by alex-silverman** [comment]
> I put a browser at the top of 04_initial_data_prep and stepped through the code. Whenever I use good.zip and I get to line 161, I get this: image and can't go further with testing.

should be fixed now!

**Pull request merged**
