### PR TITLE
Sankey chart

### PR DESCRIPTION
**Pull request by alex-silverman**
Let's hold off on merging until we merge the fixing-all-served

### CODE REVIEW

**Comment by alex-silverman** [comment]
@kiadso - note that this PR also contains Diana's changelog commits

**Comment by kiadso** [comment]
Whenever I run it on Households with Children (or likely anything that causes one of the categories to be 0) the color palette changes its associations
image

**Comment by alex-silverman** [comment]
this is proving trickier than I anticipated. Alluvials are hard to customize when it comes to colors.

**Comment by alex-silverman** [comment]
@kiadso - I think i fixed this by overlaying a geom_rect() that constructs the Begin bars.

**Review by kiadso — APPROVED** [review]
This looks great! When I use the hashed current good dataset, I see a smallish sliver where the text label is illegible. I like the idea of moving the totals out to the category names like "Exited, Permanent: 138" so there's no numbers on the bars at all, but I'll stay in my lane and leave that for VL and Jesse! :)

**Comment by alex-silverman** [comment]
merging this as the first draft of the PR.

**Pull request merged**
