### PR TITLE
Adding enrollment ID to DQ exports

### PR DESCRIPTION
**Pull request by alex-silverman**

### CODE REVIEW

**Review by kiadso — APPROVED** [review]
hey I made some quick edits, accounting for vars_prep changing. I tested on my end, looks good!

**Comment by alex-silverman** [comment]
@kiadso Nice! Thanks for catching these. I'm surprised they didn't cause errors or failed tests. Did they for you?

**Comment by kiadso** [comment]
They did not! I just checked because I've learned how tangly that vars_prep is the hard way in the past.

**Comment by alex-silverman** [comment]
just waiting on Diana to add the Project Type and Enrollment ID fields

**Comment by alex-silverman** [comment]
@zabalad - We need to change Project Type to be the abbreviations, not the numeric values. Otherwise, this looks good!

**Comment by alex-silverman** [comment]
Just waiting on @zabalad to (a) confirm the tests failed as expected and (b) update the snapshots so the tests pass

**Pull request merged**
